// Code generated by go-swagger; DO NOT EDIT.

package posts

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ua-academy-projects/share-bite/internal/guest/client/business/api/models"
)

// DeleteBusinessPostsIDReader is a Reader for the DeleteBusinessPostsID structure.
type DeleteBusinessPostsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBusinessPostsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteBusinessPostsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteBusinessPostsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteBusinessPostsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteBusinessPostsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /business/posts/{id}] DeleteBusinessPostsID", response, response.Code())
	}
}

// NewDeleteBusinessPostsIDNoContent creates a DeleteBusinessPostsIDNoContent with default headers values
func NewDeleteBusinessPostsIDNoContent() *DeleteBusinessPostsIDNoContent {
	return &DeleteBusinessPostsIDNoContent{}
}

/*
DeleteBusinessPostsIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteBusinessPostsIDNoContent struct {
}

// IsSuccess returns true when this delete business posts Id no content response has a 2xx status code
func (o *DeleteBusinessPostsIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete business posts Id no content response has a 3xx status code
func (o *DeleteBusinessPostsIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete business posts Id no content response has a 4xx status code
func (o *DeleteBusinessPostsIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete business posts Id no content response has a 5xx status code
func (o *DeleteBusinessPostsIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete business posts Id no content response a status code equal to that given
func (o *DeleteBusinessPostsIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete business posts Id no content response
func (o *DeleteBusinessPostsIDNoContent) Code() int {
	return 204
}

func (o *DeleteBusinessPostsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdNoContent", 204)
}

func (o *DeleteBusinessPostsIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdNoContent", 204)
}

func (o *DeleteBusinessPostsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBusinessPostsIDBadRequest creates a DeleteBusinessPostsIDBadRequest with default headers values
func NewDeleteBusinessPostsIDBadRequest() *DeleteBusinessPostsIDBadRequest {
	return &DeleteBusinessPostsIDBadRequest{}
}

/*
DeleteBusinessPostsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteBusinessPostsIDBadRequest struct {
	Payload *models.BusinessErrorResponse
}

// IsSuccess returns true when this delete business posts Id bad request response has a 2xx status code
func (o *DeleteBusinessPostsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete business posts Id bad request response has a 3xx status code
func (o *DeleteBusinessPostsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete business posts Id bad request response has a 4xx status code
func (o *DeleteBusinessPostsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete business posts Id bad request response has a 5xx status code
func (o *DeleteBusinessPostsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete business posts Id bad request response a status code equal to that given
func (o *DeleteBusinessPostsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete business posts Id bad request response
func (o *DeleteBusinessPostsIDBadRequest) Code() int {
	return 400
}

func (o *DeleteBusinessPostsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdBadRequest %s", 400, payload)
}

func (o *DeleteBusinessPostsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdBadRequest %s", 400, payload)
}

func (o *DeleteBusinessPostsIDBadRequest) GetPayload() *models.BusinessErrorResponse {
	return o.Payload
}

func (o *DeleteBusinessPostsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteBusinessPostsIDForbidden creates a DeleteBusinessPostsIDForbidden with default headers values
func NewDeleteBusinessPostsIDForbidden() *DeleteBusinessPostsIDForbidden {
	return &DeleteBusinessPostsIDForbidden{}
}

/*
DeleteBusinessPostsIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteBusinessPostsIDForbidden struct {
	Payload *models.BusinessErrorResponse
}

// IsSuccess returns true when this delete business posts Id forbidden response has a 2xx status code
func (o *DeleteBusinessPostsIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete business posts Id forbidden response has a 3xx status code
func (o *DeleteBusinessPostsIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete business posts Id forbidden response has a 4xx status code
func (o *DeleteBusinessPostsIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete business posts Id forbidden response has a 5xx status code
func (o *DeleteBusinessPostsIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete business posts Id forbidden response a status code equal to that given
func (o *DeleteBusinessPostsIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete business posts Id forbidden response
func (o *DeleteBusinessPostsIDForbidden) Code() int {
	return 403
}

func (o *DeleteBusinessPostsIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdForbidden %s", 403, payload)
}

func (o *DeleteBusinessPostsIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdForbidden %s", 403, payload)
}

func (o *DeleteBusinessPostsIDForbidden) GetPayload() *models.BusinessErrorResponse {
	return o.Payload
}

func (o *DeleteBusinessPostsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteBusinessPostsIDInternalServerError creates a DeleteBusinessPostsIDInternalServerError with default headers values
func NewDeleteBusinessPostsIDInternalServerError() *DeleteBusinessPostsIDInternalServerError {
	return &DeleteBusinessPostsIDInternalServerError{}
}

/*
DeleteBusinessPostsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteBusinessPostsIDInternalServerError struct {
	Payload *models.BusinessErrorResponse
}

// IsSuccess returns true when this delete business posts Id internal server error response has a 2xx status code
func (o *DeleteBusinessPostsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete business posts Id internal server error response has a 3xx status code
func (o *DeleteBusinessPostsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete business posts Id internal server error response has a 4xx status code
func (o *DeleteBusinessPostsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete business posts Id internal server error response has a 5xx status code
func (o *DeleteBusinessPostsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete business posts Id internal server error response a status code equal to that given
func (o *DeleteBusinessPostsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete business posts Id internal server error response
func (o *DeleteBusinessPostsIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteBusinessPostsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdInternalServerError %s", 500, payload)
}

func (o *DeleteBusinessPostsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /business/posts/{id}][%d] deleteBusinessPostsIdInternalServerError %s", 500, payload)
}

func (o *DeleteBusinessPostsIDInternalServerError) GetPayload() *models.BusinessErrorResponse {
	return o.Payload
}

func (o *DeleteBusinessPostsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
