// Code generated by go-swagger; DO NOT EDIT.

package posts

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/client/business/api/models"
)

// GetBusinessPostsReader is a Reader for the GetBusinessPosts structure.
type GetBusinessPostsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBusinessPostsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetBusinessPostsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBusinessPostsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBusinessPostsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /business/posts] GetBusinessPosts", response, response.Code())
	}
}

// NewGetBusinessPostsOK creates a GetBusinessPostsOK with default headers values
func NewGetBusinessPostsOK() *GetBusinessPostsOK {
	return &GetBusinessPostsOK{}
}

/*
GetBusinessPostsOK describes a response with status code 200, with default header values.

OK
*/
type GetBusinessPostsOK struct {
	Payload *models.BusinessGetPostsResponse
}

// IsSuccess returns true when this get business posts o k response has a 2xx status code
func (o *GetBusinessPostsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get business posts o k response has a 3xx status code
func (o *GetBusinessPostsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business posts o k response has a 4xx status code
func (o *GetBusinessPostsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business posts o k response has a 5xx status code
func (o *GetBusinessPostsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get business posts o k response a status code equal to that given
func (o *GetBusinessPostsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get business posts o k response
func (o *GetBusinessPostsOK) Code() int {
	return 200
}

func (o *GetBusinessPostsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/posts][%d] getBusinessPostsOK %s", 200, payload)
}

func (o *GetBusinessPostsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/posts][%d] getBusinessPostsOK %s", 200, payload)
}

func (o *GetBusinessPostsOK) GetPayload() *models.BusinessGetPostsResponse {
	return o.Payload
}

func (o *GetBusinessPostsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BusinessGetPostsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessPostsBadRequest creates a GetBusinessPostsBadRequest with default headers values
func NewGetBusinessPostsBadRequest() *GetBusinessPostsBadRequest {
	return &GetBusinessPostsBadRequest{}
}

/*
GetBusinessPostsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetBusinessPostsBadRequest struct {
	Payload *models.BusinessErrorResponse
}

// IsSuccess returns true when this get business posts bad request response has a 2xx status code
func (o *GetBusinessPostsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business posts bad request response has a 3xx status code
func (o *GetBusinessPostsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business posts bad request response has a 4xx status code
func (o *GetBusinessPostsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get business posts bad request response has a 5xx status code
func (o *GetBusinessPostsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get business posts bad request response a status code equal to that given
func (o *GetBusinessPostsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get business posts bad request response
func (o *GetBusinessPostsBadRequest) Code() int {
	return 400
}

func (o *GetBusinessPostsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/posts][%d] getBusinessPostsBadRequest %s", 400, payload)
}

func (o *GetBusinessPostsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/posts][%d] getBusinessPostsBadRequest %s", 400, payload)
}

func (o *GetBusinessPostsBadRequest) GetPayload() *models.BusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessPostsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessPostsInternalServerError creates a GetBusinessPostsInternalServerError with default headers values
func NewGetBusinessPostsInternalServerError() *GetBusinessPostsInternalServerError {
	return &GetBusinessPostsInternalServerError{}
}

/*
GetBusinessPostsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetBusinessPostsInternalServerError struct {
	Payload *models.BusinessErrorResponse
}

// IsSuccess returns true when this get business posts internal server error response has a 2xx status code
func (o *GetBusinessPostsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business posts internal server error response has a 3xx status code
func (o *GetBusinessPostsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business posts internal server error response has a 4xx status code
func (o *GetBusinessPostsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business posts internal server error response has a 5xx status code
func (o *GetBusinessPostsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get business posts internal server error response a status code equal to that given
func (o *GetBusinessPostsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get business posts internal server error response
func (o *GetBusinessPostsInternalServerError) Code() int {
	return 500
}

func (o *GetBusinessPostsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/posts][%d] getBusinessPostsInternalServerError %s", 500, payload)
}

func (o *GetBusinessPostsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/posts][%d] getBusinessPostsInternalServerError %s", 500, payload)
}

func (o *GetBusinessPostsInternalServerError) GetPayload() *models.BusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessPostsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
