// Code generated by go-swagger; DO NOT EDIT.

package posts

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBusinessPostsParams creates a new GetBusinessPostsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBusinessPostsParams() *GetBusinessPostsParams {
	return &GetBusinessPostsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBusinessPostsParamsWithTimeout creates a new GetBusinessPostsParams object
// with the ability to set a timeout on a request.
func NewGetBusinessPostsParamsWithTimeout(timeout time.Duration) *GetBusinessPostsParams {
	return &GetBusinessPostsParams{
		timeout: timeout,
	}
}

// NewGetBusinessPostsParamsWithContext creates a new GetBusinessPostsParams object
// with the ability to set a context for a request.
func NewGetBusinessPostsParamsWithContext(ctx context.Context) *GetBusinessPostsParams {
	return &GetBusinessPostsParams{
		Context: ctx,
	}
}

// NewGetBusinessPostsParamsWithHTTPClient creates a new GetBusinessPostsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBusinessPostsParamsWithHTTPClient(client *http.Client) *GetBusinessPostsParams {
	return &GetBusinessPostsParams{
		HTTPClient: client,
	}
}

/*
GetBusinessPostsParams contains all the parameters to send to the API endpoint

	for the get business posts operation.

	Typically these are written to a http.Request.
*/
type GetBusinessPostsParams struct {

	/* Limit.

	   Number of items to return (default: 10, max: 100)
	*/
	Limit *int64

	/* Skip.

	   Number of items to skip (default: 0)
	*/
	Skip *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get business posts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessPostsParams) WithDefaults() *GetBusinessPostsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get business posts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessPostsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get business posts params
func (o *GetBusinessPostsParams) WithTimeout(timeout time.Duration) *GetBusinessPostsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get business posts params
func (o *GetBusinessPostsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get business posts params
func (o *GetBusinessPostsParams) WithContext(ctx context.Context) *GetBusinessPostsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get business posts params
func (o *GetBusinessPostsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get business posts params
func (o *GetBusinessPostsParams) WithHTTPClient(client *http.Client) *GetBusinessPostsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get business posts params
func (o *GetBusinessPostsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get business posts params
func (o *GetBusinessPostsParams) WithLimit(limit *int64) *GetBusinessPostsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get business posts params
func (o *GetBusinessPostsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSkip adds the skip to the get business posts params
func (o *GetBusinessPostsParams) WithSkip(skip *int64) *GetBusinessPostsParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the get business posts params
func (o *GetBusinessPostsParams) SetSkip(skip *int64) {
	o.Skip = skip
}

// WriteToRequest writes these params to a swagger request
func (o *GetBusinessPostsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int64

		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt64(qrSkip)
		if qSkip != "" {

			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
