// Code generated by go-swagger; DO NOT EDIT.

package posts

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new posts API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new posts API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new posts API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for posts API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteBusinessPostsID(params *DeleteBusinessPostsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteBusinessPostsIDNoContent, error)

	GetBusinessPosts(params *GetBusinessPostsParams, opts ...ClientOption) (*GetBusinessPostsOK, error)

	PutBusinessPostsID(params *PutBusinessPostsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutBusinessPostsIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteBusinessPostsID deletes post

Deletes a post if the user has permission (owner of the org)
*/
func (a *Client) DeleteBusinessPostsID(params *DeleteBusinessPostsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteBusinessPostsIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteBusinessPostsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteBusinessPostsID",
		Method:             "DELETE",
		PathPattern:        "/business/posts/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteBusinessPostsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteBusinessPostsIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteBusinessPostsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetBusinessPosts gets posts

Returns paginated posts with images and organization info
*/
func (a *Client) GetBusinessPosts(params *GetBusinessPostsParams, opts ...ClientOption) (*GetBusinessPostsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetBusinessPostsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetBusinessPosts",
		Method:             "GET",
		PathPattern:        "/business/posts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBusinessPostsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetBusinessPostsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetBusinessPosts: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutBusinessPostsID updates post

Updates the content of a post if the user has permission
*/
func (a *Client) PutBusinessPostsID(params *PutBusinessPostsIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PutBusinessPostsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutBusinessPostsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutBusinessPostsID",
		Method:             "PUT",
		PathPattern:        "/business/posts/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutBusinessPostsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutBusinessPostsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutBusinessPostsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
