// Code generated by go-swagger; DO NOT EDIT.

package posts

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/ua-academy-projects/share-bite/internal/guest/client/business/api/models"
)

// NewPutBusinessPostsIDParams creates a new PutBusinessPostsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutBusinessPostsIDParams() *PutBusinessPostsIDParams {
	return &PutBusinessPostsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutBusinessPostsIDParamsWithTimeout creates a new PutBusinessPostsIDParams object
// with the ability to set a timeout on a request.
func NewPutBusinessPostsIDParamsWithTimeout(timeout time.Duration) *PutBusinessPostsIDParams {
	return &PutBusinessPostsIDParams{
		timeout: timeout,
	}
}

// NewPutBusinessPostsIDParamsWithContext creates a new PutBusinessPostsIDParams object
// with the ability to set a context for a request.
func NewPutBusinessPostsIDParamsWithContext(ctx context.Context) *PutBusinessPostsIDParams {
	return &PutBusinessPostsIDParams{
		Context: ctx,
	}
}

// NewPutBusinessPostsIDParamsWithHTTPClient creates a new PutBusinessPostsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutBusinessPostsIDParamsWithHTTPClient(client *http.Client) *PutBusinessPostsIDParams {
	return &PutBusinessPostsIDParams{
		HTTPClient: client,
	}
}

/*
PutBusinessPostsIDParams contains all the parameters to send to the API endpoint

	for the put business posts ID operation.

	Typically these are written to a http.Request.
*/
type PutBusinessPostsIDParams struct {

	/* ID.

	   Post ID
	*/
	ID int64

	/* Input.

	   Updated post content
	*/
	Input *models.BusinessUpdatePostRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put business posts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBusinessPostsIDParams) WithDefaults() *PutBusinessPostsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put business posts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBusinessPostsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put business posts ID params
func (o *PutBusinessPostsIDParams) WithTimeout(timeout time.Duration) *PutBusinessPostsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put business posts ID params
func (o *PutBusinessPostsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put business posts ID params
func (o *PutBusinessPostsIDParams) WithContext(ctx context.Context) *PutBusinessPostsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put business posts ID params
func (o *PutBusinessPostsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put business posts ID params
func (o *PutBusinessPostsIDParams) WithHTTPClient(client *http.Client) *PutBusinessPostsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put business posts ID params
func (o *PutBusinessPostsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put business posts ID params
func (o *PutBusinessPostsIDParams) WithID(id int64) *PutBusinessPostsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put business posts ID params
func (o *PutBusinessPostsIDParams) SetID(id int64) {
	o.ID = id
}

// WithInput adds the input to the put business posts ID params
func (o *PutBusinessPostsIDParams) WithInput(input *models.BusinessUpdatePostRequest) *PutBusinessPostsIDParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the put business posts ID params
func (o *PutBusinessPostsIDParams) SetInput(input *models.BusinessUpdatePostRequest) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PutBusinessPostsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
