apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-api
  namespace: share-bite-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-api
  template:
    metadata:
      labels:
        app: business-api
    spec:
      containers:
        - name: business-api
          image: business-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3900
          envFrom:
            - configMapRef:
                name: share-bite-infra-config
            - configMapRef:
                name: share-bite-business-config
            - secretRef:
                name: share-bite-secrets
          readinessProbe:
            httpGet:
              path: /business/ready
              port: 3900
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /business/healthz
              port: 3900
            initialDelaySeconds: 15
            periodSeconds: 20
