-- +goose Up
GRANT USAGE ON SCHEMA business TO share;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA business TO share;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA business TO share;

ALTER DEFAULT PRIVILEGES IN SCHEMA business GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO share;

ALTER DEFAULT PRIVILEGES IN SCHEMA business GRANT USAGE, SELECT ON SEQUENCES TO share;


-- +goose Down
ALTER DEFAULT PRIVILEGES IN SCHEMA business REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM share;
ALTER DEFAULT PRIVILEGES IN SCHEMA business REVOKE USAGE, SELECT ON SEQUENCES FROM share;

REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA business FROM share;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA business FROM share;
REVOKE USAGE ON SCHEMA business FROM share;