-- +goose Up
CREATE TABLE IF NOT EXISTS guest.post_images (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                 post_id BIGINT NOT NULL
                                                 REFERENCES guest.posts(id) ON DELETE CASCADE,

    object_key VARCHAR(255) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT post_images_file_size_chk
    CHECK (file_size > 0),

    CONSTRAINT post_images_sort_order_chk
    CHECK (sort_order >= 0),

    CONSTRAINT post_images_content_type_chk
    CHECK (content_type IN ('image/jpeg', 'image/png'))
    );

CREATE INDEX IF NOT EXISTS idx_post_images_post_id
    ON guest.post_images(post_id);