-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS guest.customer_follows
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    follower_customer_id UUID NOT NULL
    REFERENCES guest.customers(id) ON DELETE CASCADE,

    followed_customer_id UUID NOT NULL
    REFERENCES guest.customers(id) ON DELETE CASCADE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT customer_follows_unique
    UNIQUE (follower_customer_id, followed_customer_id),

    CONSTRAINT customer_follows_no_self
    CHECK (follower_customer_id <> followed_customer_id)
    );

CREATE INDEX IF NOT EXISTS idx_customer_follows_follower
    ON guest.customer_follows(follower_customer_id);

CREATE INDEX IF NOT EXISTS idx_customer_follows_followed
    ON guest.customer_follows(followed_customer_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS guest.customer_follows;
-- +goose StatementEnd