// Code generated by go-swagger; DO NOT EDIT.

package posts

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteBusinessPostsIDParams creates a new DeleteBusinessPostsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBusinessPostsIDParams() *DeleteBusinessPostsIDParams {
	return &DeleteBusinessPostsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBusinessPostsIDParamsWithTimeout creates a new DeleteBusinessPostsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteBusinessPostsIDParamsWithTimeout(timeout time.Duration) *DeleteBusinessPostsIDParams {
	return &DeleteBusinessPostsIDParams{
		timeout: timeout,
	}
}

// NewDeleteBusinessPostsIDParamsWithContext creates a new DeleteBusinessPostsIDParams object
// with the ability to set a context for a request.
func NewDeleteBusinessPostsIDParamsWithContext(ctx context.Context) *DeleteBusinessPostsIDParams {
	return &DeleteBusinessPostsIDParams{
		Context: ctx,
	}
}

// NewDeleteBusinessPostsIDParamsWithHTTPClient creates a new DeleteBusinessPostsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBusinessPostsIDParamsWithHTTPClient(client *http.Client) *DeleteBusinessPostsIDParams {
	return &DeleteBusinessPostsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteBusinessPostsIDParams contains all the parameters to send to the API endpoint

	for the delete business posts ID operation.

	Typically these are written to a http.Request.
*/
type DeleteBusinessPostsIDParams struct {

	/* ID.

	   Post ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete business posts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBusinessPostsIDParams) WithDefaults() *DeleteBusinessPostsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete business posts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBusinessPostsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) WithTimeout(timeout time.Duration) *DeleteBusinessPostsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) WithContext(ctx context.Context) *DeleteBusinessPostsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) WithHTTPClient(client *http.Client) *DeleteBusinessPostsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) WithID(id int64) *DeleteBusinessPostsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete business posts ID params
func (o *DeleteBusinessPostsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBusinessPostsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
