// Code generated by go-swagger; DO NOT EDIT.

package posts

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// PutBusinessPostsIDReader is a Reader for the PutBusinessPostsID structure.
type PutBusinessPostsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutBusinessPostsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutBusinessPostsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutBusinessPostsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutBusinessPostsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutBusinessPostsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutBusinessPostsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutBusinessPostsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /business/posts/{id}] PutBusinessPostsID", response, response.Code())
	}
}

// NewPutBusinessPostsIDOK creates a PutBusinessPostsIDOK with default headers values
func NewPutBusinessPostsIDOK() *PutBusinessPostsIDOK {
	return &PutBusinessPostsIDOK{}
}

/*
PutBusinessPostsIDOK describes a response with status code 200, with default header values.

OK
*/
type PutBusinessPostsIDOK struct {
	Payload *dto.DtoPostResponse
}

// IsSuccess returns true when this put business posts Id o k response has a 2xx status code
func (o *PutBusinessPostsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put business posts Id o k response has a 3xx status code
func (o *PutBusinessPostsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put business posts Id o k response has a 4xx status code
func (o *PutBusinessPostsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put business posts Id o k response has a 5xx status code
func (o *PutBusinessPostsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put business posts Id o k response a status code equal to that given
func (o *PutBusinessPostsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put business posts Id o k response
func (o *PutBusinessPostsIDOK) Code() int {
	return 200
}

func (o *PutBusinessPostsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdOK %s", 200, payload)
}

func (o *PutBusinessPostsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdOK %s", 200, payload)
}

func (o *PutBusinessPostsIDOK) GetPayload() *dto.DtoPostResponse {
	return o.Payload
}

func (o *PutBusinessPostsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.DtoPostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutBusinessPostsIDBadRequest creates a PutBusinessPostsIDBadRequest with default headers values
func NewPutBusinessPostsIDBadRequest() *PutBusinessPostsIDBadRequest {
	return &PutBusinessPostsIDBadRequest{}
}

/*
PutBusinessPostsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutBusinessPostsIDBadRequest struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this put business posts Id bad request response has a 2xx status code
func (o *PutBusinessPostsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put business posts Id bad request response has a 3xx status code
func (o *PutBusinessPostsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put business posts Id bad request response has a 4xx status code
func (o *PutBusinessPostsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put business posts Id bad request response has a 5xx status code
func (o *PutBusinessPostsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put business posts Id bad request response a status code equal to that given
func (o *PutBusinessPostsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put business posts Id bad request response
func (o *PutBusinessPostsIDBadRequest) Code() int {
	return 400
}

func (o *PutBusinessPostsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdBadRequest %s", 400, payload)
}

func (o *PutBusinessPostsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdBadRequest %s", 400, payload)
}

func (o *PutBusinessPostsIDBadRequest) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PutBusinessPostsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutBusinessPostsIDUnauthorized creates a PutBusinessPostsIDUnauthorized with default headers values
func NewPutBusinessPostsIDUnauthorized() *PutBusinessPostsIDUnauthorized {
	return &PutBusinessPostsIDUnauthorized{}
}

/*
PutBusinessPostsIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PutBusinessPostsIDUnauthorized struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this put business posts Id unauthorized response has a 2xx status code
func (o *PutBusinessPostsIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put business posts Id unauthorized response has a 3xx status code
func (o *PutBusinessPostsIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put business posts Id unauthorized response has a 4xx status code
func (o *PutBusinessPostsIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this put business posts Id unauthorized response has a 5xx status code
func (o *PutBusinessPostsIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this put business posts Id unauthorized response a status code equal to that given
func (o *PutBusinessPostsIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the put business posts Id unauthorized response
func (o *PutBusinessPostsIDUnauthorized) Code() int {
	return 401
}

func (o *PutBusinessPostsIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdUnauthorized %s", 401, payload)
}

func (o *PutBusinessPostsIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdUnauthorized %s", 401, payload)
}

func (o *PutBusinessPostsIDUnauthorized) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PutBusinessPostsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutBusinessPostsIDForbidden creates a PutBusinessPostsIDForbidden with default headers values
func NewPutBusinessPostsIDForbidden() *PutBusinessPostsIDForbidden {
	return &PutBusinessPostsIDForbidden{}
}

/*
PutBusinessPostsIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PutBusinessPostsIDForbidden struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this put business posts Id forbidden response has a 2xx status code
func (o *PutBusinessPostsIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put business posts Id forbidden response has a 3xx status code
func (o *PutBusinessPostsIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put business posts Id forbidden response has a 4xx status code
func (o *PutBusinessPostsIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this put business posts Id forbidden response has a 5xx status code
func (o *PutBusinessPostsIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this put business posts Id forbidden response a status code equal to that given
func (o *PutBusinessPostsIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the put business posts Id forbidden response
func (o *PutBusinessPostsIDForbidden) Code() int {
	return 403
}

func (o *PutBusinessPostsIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdForbidden %s", 403, payload)
}

func (o *PutBusinessPostsIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdForbidden %s", 403, payload)
}

func (o *PutBusinessPostsIDForbidden) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PutBusinessPostsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutBusinessPostsIDNotFound creates a PutBusinessPostsIDNotFound with default headers values
func NewPutBusinessPostsIDNotFound() *PutBusinessPostsIDNotFound {
	return &PutBusinessPostsIDNotFound{}
}

/*
PutBusinessPostsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutBusinessPostsIDNotFound struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this put business posts Id not found response has a 2xx status code
func (o *PutBusinessPostsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put business posts Id not found response has a 3xx status code
func (o *PutBusinessPostsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put business posts Id not found response has a 4xx status code
func (o *PutBusinessPostsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put business posts Id not found response has a 5xx status code
func (o *PutBusinessPostsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put business posts Id not found response a status code equal to that given
func (o *PutBusinessPostsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put business posts Id not found response
func (o *PutBusinessPostsIDNotFound) Code() int {
	return 404
}

func (o *PutBusinessPostsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdNotFound %s", 404, payload)
}

func (o *PutBusinessPostsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdNotFound %s", 404, payload)
}

func (o *PutBusinessPostsIDNotFound) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PutBusinessPostsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutBusinessPostsIDInternalServerError creates a PutBusinessPostsIDInternalServerError with default headers values
func NewPutBusinessPostsIDInternalServerError() *PutBusinessPostsIDInternalServerError {
	return &PutBusinessPostsIDInternalServerError{}
}

/*
PutBusinessPostsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutBusinessPostsIDInternalServerError struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this put business posts Id internal server error response has a 2xx status code
func (o *PutBusinessPostsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put business posts Id internal server error response has a 3xx status code
func (o *PutBusinessPostsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put business posts Id internal server error response has a 4xx status code
func (o *PutBusinessPostsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put business posts Id internal server error response has a 5xx status code
func (o *PutBusinessPostsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put business posts Id internal server error response a status code equal to that given
func (o *PutBusinessPostsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put business posts Id internal server error response
func (o *PutBusinessPostsIDInternalServerError) Code() int {
	return 500
}

func (o *PutBusinessPostsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdInternalServerError %s", 500, payload)
}

func (o *PutBusinessPostsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /business/posts/{id}][%d] putBusinessPostsIdInternalServerError %s", 500, payload)
}

func (o *PutBusinessPostsIDInternalServerError) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PutBusinessPostsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
