// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/client/business/api/models"
)

// NewPostAuthResetPasswordParams creates a new PostAuthResetPasswordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthResetPasswordParams() *PostAuthResetPasswordParams {
	return &PostAuthResetPasswordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthResetPasswordParamsWithTimeout creates a new PostAuthResetPasswordParams object
// with the ability to set a timeout on a request.
func NewPostAuthResetPasswordParamsWithTimeout(timeout time.Duration) *PostAuthResetPasswordParams {
	return &PostAuthResetPasswordParams{
		timeout: timeout,
	}
}

// NewPostAuthResetPasswordParamsWithContext creates a new PostAuthResetPasswordParams object
// with the ability to set a context for a request.
func NewPostAuthResetPasswordParamsWithContext(ctx context.Context) *PostAuthResetPasswordParams {
	return &PostAuthResetPasswordParams{
		Context: ctx,
	}
}

// NewPostAuthResetPasswordParamsWithHTTPClient creates a new PostAuthResetPasswordParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthResetPasswordParamsWithHTTPClient(client *http.Client) *PostAuthResetPasswordParams {
	return &PostAuthResetPasswordParams{
		HTTPClient: client,
	}
}

/*
PostAuthResetPasswordParams contains all the parameters to send to the API endpoint

	for the post auth reset password operation.

	Typically these are written to a http.Request.
*/
type PostAuthResetPasswordParams struct {

	/* Request.

	   Reset password payload
	*/
	Request *models.AuthResetPasswordRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth reset password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthResetPasswordParams) WithDefaults() *PostAuthResetPasswordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth reset password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthResetPasswordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth reset password params
func (o *PostAuthResetPasswordParams) WithTimeout(timeout time.Duration) *PostAuthResetPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth reset password params
func (o *PostAuthResetPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth reset password params
func (o *PostAuthResetPasswordParams) WithContext(ctx context.Context) *PostAuthResetPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth reset password params
func (o *PostAuthResetPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth reset password params
func (o *PostAuthResetPasswordParams) WithHTTPClient(client *http.Client) *PostAuthResetPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth reset password params
func (o *PostAuthResetPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post auth reset password params
func (o *PostAuthResetPasswordParams) WithRequest(request *models.AuthResetPasswordRequest) *PostAuthResetPasswordParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post auth reset password params
func (o *PostAuthResetPasswordParams) SetRequest(request *models.AuthResetPasswordRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthResetPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
