// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/client/business/api/models"
)

// PostAuthResetPasswordReader is a Reader for the PostAuthResetPassword structure.
type PostAuthResetPasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthResetPasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthResetPasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthResetPasswordBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAuthResetPasswordInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/reset-password] PostAuthResetPassword", response, response.Code())
	}
}

// NewPostAuthResetPasswordOK creates a PostAuthResetPasswordOK with default headers values
func NewPostAuthResetPasswordOK() *PostAuthResetPasswordOK {
	return &PostAuthResetPasswordOK{}
}

/*
PostAuthResetPasswordOK describes a response with status code 200, with default header values.

OK
*/
type PostAuthResetPasswordOK struct {
	Payload *models.AuthMessageResponse
}

// IsSuccess returns true when this post auth reset password o k response has a 2xx status code
func (o *PostAuthResetPasswordOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth reset password o k response has a 3xx status code
func (o *PostAuthResetPasswordOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth reset password o k response has a 4xx status code
func (o *PostAuthResetPasswordOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth reset password o k response has a 5xx status code
func (o *PostAuthResetPasswordOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth reset password o k response a status code equal to that given
func (o *PostAuthResetPasswordOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post auth reset password o k response
func (o *PostAuthResetPasswordOK) Code() int {
	return 200
}

func (o *PostAuthResetPasswordOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/reset-password][%d] postAuthResetPasswordOK %s", 200, payload)
}

func (o *PostAuthResetPasswordOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/reset-password][%d] postAuthResetPasswordOK %s", 200, payload)
}

func (o *PostAuthResetPasswordOK) GetPayload() *models.AuthMessageResponse {
	return o.Payload
}

func (o *PostAuthResetPasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthResetPasswordBadRequest creates a PostAuthResetPasswordBadRequest with default headers values
func NewPostAuthResetPasswordBadRequest() *PostAuthResetPasswordBadRequest {
	return &PostAuthResetPasswordBadRequest{}
}

/*
PostAuthResetPasswordBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAuthResetPasswordBadRequest struct {
	Payload *models.AuthErrorResponse
}

// IsSuccess returns true when this post auth reset password bad request response has a 2xx status code
func (o *PostAuthResetPasswordBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth reset password bad request response has a 3xx status code
func (o *PostAuthResetPasswordBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth reset password bad request response has a 4xx status code
func (o *PostAuthResetPasswordBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth reset password bad request response has a 5xx status code
func (o *PostAuthResetPasswordBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth reset password bad request response a status code equal to that given
func (o *PostAuthResetPasswordBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post auth reset password bad request response
func (o *PostAuthResetPasswordBadRequest) Code() int {
	return 400
}

func (o *PostAuthResetPasswordBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/reset-password][%d] postAuthResetPasswordBadRequest %s", 400, payload)
}

func (o *PostAuthResetPasswordBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/reset-password][%d] postAuthResetPasswordBadRequest %s", 400, payload)
}

func (o *PostAuthResetPasswordBadRequest) GetPayload() *models.AuthErrorResponse {
	return o.Payload
}

func (o *PostAuthResetPasswordBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthResetPasswordInternalServerError creates a PostAuthResetPasswordInternalServerError with default headers values
func NewPostAuthResetPasswordInternalServerError() *PostAuthResetPasswordInternalServerError {
	return &PostAuthResetPasswordInternalServerError{}
}

/*
PostAuthResetPasswordInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAuthResetPasswordInternalServerError struct {
	Payload *models.AuthErrorResponse
}

// IsSuccess returns true when this post auth reset password internal server error response has a 2xx status code
func (o *PostAuthResetPasswordInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth reset password internal server error response has a 3xx status code
func (o *PostAuthResetPasswordInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth reset password internal server error response has a 4xx status code
func (o *PostAuthResetPasswordInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth reset password internal server error response has a 5xx status code
func (o *PostAuthResetPasswordInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post auth reset password internal server error response a status code equal to that given
func (o *PostAuthResetPasswordInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post auth reset password internal server error response
func (o *PostAuthResetPasswordInternalServerError) Code() int {
	return 500
}

func (o *PostAuthResetPasswordInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/reset-password][%d] postAuthResetPasswordInternalServerError %s", 500, payload)
}

func (o *PostAuthResetPasswordInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/reset-password][%d] postAuthResetPasswordInternalServerError %s", 500, payload)
}

func (o *PostAuthResetPasswordInternalServerError) GetPayload() *models.AuthErrorResponse {
	return o.Payload
}

func (o *PostAuthResetPasswordInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
