// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/client/business/api/models"
)

// NewPostAuthRecoverAccessParams creates a new PostAuthRecoverAccessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthRecoverAccessParams() *PostAuthRecoverAccessParams {
	return &PostAuthRecoverAccessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthRecoverAccessParamsWithTimeout creates a new PostAuthRecoverAccessParams object
// with the ability to set a timeout on a request.
func NewPostAuthRecoverAccessParamsWithTimeout(timeout time.Duration) *PostAuthRecoverAccessParams {
	return &PostAuthRecoverAccessParams{
		timeout: timeout,
	}
}

// NewPostAuthRecoverAccessParamsWithContext creates a new PostAuthRecoverAccessParams object
// with the ability to set a context for a request.
func NewPostAuthRecoverAccessParamsWithContext(ctx context.Context) *PostAuthRecoverAccessParams {
	return &PostAuthRecoverAccessParams{
		Context: ctx,
	}
}

// NewPostAuthRecoverAccessParamsWithHTTPClient creates a new PostAuthRecoverAccessParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthRecoverAccessParamsWithHTTPClient(client *http.Client) *PostAuthRecoverAccessParams {
	return &PostAuthRecoverAccessParams{
		HTTPClient: client,
	}
}

/*
PostAuthRecoverAccessParams contains all the parameters to send to the API endpoint

	for the post auth recover access operation.

	Typically these are written to a http.Request.
*/
type PostAuthRecoverAccessParams struct {

	/* Request.

	   Recover access payload
	*/
	Request *models.AuthRecoverAccessRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth recover access params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthRecoverAccessParams) WithDefaults() *PostAuthRecoverAccessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth recover access params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthRecoverAccessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth recover access params
func (o *PostAuthRecoverAccessParams) WithTimeout(timeout time.Duration) *PostAuthRecoverAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth recover access params
func (o *PostAuthRecoverAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth recover access params
func (o *PostAuthRecoverAccessParams) WithContext(ctx context.Context) *PostAuthRecoverAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth recover access params
func (o *PostAuthRecoverAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth recover access params
func (o *PostAuthRecoverAccessParams) WithHTTPClient(client *http.Client) *PostAuthRecoverAccessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth recover access params
func (o *PostAuthRecoverAccessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post auth recover access params
func (o *PostAuthRecoverAccessParams) WithRequest(request *models.AuthRecoverAccessRequest) *PostAuthRecoverAccessParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post auth recover access params
func (o *PostAuthRecoverAccessParams) SetRequest(request *models.AuthRecoverAccessRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthRecoverAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
