// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/client/business/api/models"
)

// PostAuthRecoverAccessReader is a Reader for the PostAuthRecoverAccess structure.
type PostAuthRecoverAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthRecoverAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthRecoverAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthRecoverAccessBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAuthRecoverAccessInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/recover-access] PostAuthRecoverAccess", response, response.Code())
	}
}

// NewPostAuthRecoverAccessOK creates a PostAuthRecoverAccessOK with default headers values
func NewPostAuthRecoverAccessOK() *PostAuthRecoverAccessOK {
	return &PostAuthRecoverAccessOK{}
}

/*
PostAuthRecoverAccessOK describes a response with status code 200, with default header values.

OK
*/
type PostAuthRecoverAccessOK struct {
	Payload *models.AuthMessageResponse
}

// IsSuccess returns true when this post auth recover access o k response has a 2xx status code
func (o *PostAuthRecoverAccessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth recover access o k response has a 3xx status code
func (o *PostAuthRecoverAccessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth recover access o k response has a 4xx status code
func (o *PostAuthRecoverAccessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth recover access o k response has a 5xx status code
func (o *PostAuthRecoverAccessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth recover access o k response a status code equal to that given
func (o *PostAuthRecoverAccessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post auth recover access o k response
func (o *PostAuthRecoverAccessOK) Code() int {
	return 200
}

func (o *PostAuthRecoverAccessOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/recover-access][%d] postAuthRecoverAccessOK %s", 200, payload)
}

func (o *PostAuthRecoverAccessOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/recover-access][%d] postAuthRecoverAccessOK %s", 200, payload)
}

func (o *PostAuthRecoverAccessOK) GetPayload() *models.AuthMessageResponse {
	return o.Payload
}

func (o *PostAuthRecoverAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthRecoverAccessBadRequest creates a PostAuthRecoverAccessBadRequest with default headers values
func NewPostAuthRecoverAccessBadRequest() *PostAuthRecoverAccessBadRequest {
	return &PostAuthRecoverAccessBadRequest{}
}

/*
PostAuthRecoverAccessBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAuthRecoverAccessBadRequest struct {
	Payload *models.AuthErrorResponse
}

// IsSuccess returns true when this post auth recover access bad request response has a 2xx status code
func (o *PostAuthRecoverAccessBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth recover access bad request response has a 3xx status code
func (o *PostAuthRecoverAccessBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth recover access bad request response has a 4xx status code
func (o *PostAuthRecoverAccessBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth recover access bad request response has a 5xx status code
func (o *PostAuthRecoverAccessBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth recover access bad request response a status code equal to that given
func (o *PostAuthRecoverAccessBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post auth recover access bad request response
func (o *PostAuthRecoverAccessBadRequest) Code() int {
	return 400
}

func (o *PostAuthRecoverAccessBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/recover-access][%d] postAuthRecoverAccessBadRequest %s", 400, payload)
}

func (o *PostAuthRecoverAccessBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/recover-access][%d] postAuthRecoverAccessBadRequest %s", 400, payload)
}

func (o *PostAuthRecoverAccessBadRequest) GetPayload() *models.AuthErrorResponse {
	return o.Payload
}

func (o *PostAuthRecoverAccessBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAuthRecoverAccessInternalServerError creates a PostAuthRecoverAccessInternalServerError with default headers values
func NewPostAuthRecoverAccessInternalServerError() *PostAuthRecoverAccessInternalServerError {
	return &PostAuthRecoverAccessInternalServerError{}
}

/*
PostAuthRecoverAccessInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAuthRecoverAccessInternalServerError struct {
	Payload *models.AuthErrorResponse
}

// IsSuccess returns true when this post auth recover access internal server error response has a 2xx status code
func (o *PostAuthRecoverAccessInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth recover access internal server error response has a 3xx status code
func (o *PostAuthRecoverAccessInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth recover access internal server error response has a 4xx status code
func (o *PostAuthRecoverAccessInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth recover access internal server error response has a 5xx status code
func (o *PostAuthRecoverAccessInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post auth recover access internal server error response a status code equal to that given
func (o *PostAuthRecoverAccessInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post auth recover access internal server error response
func (o *PostAuthRecoverAccessInternalServerError) Code() int {
	return 500
}

func (o *PostAuthRecoverAccessInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/recover-access][%d] postAuthRecoverAccessInternalServerError %s", 500, payload)
}

func (o *PostAuthRecoverAccessInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/recover-access][%d] postAuthRecoverAccessInternalServerError %s", 500, payload)
}

func (o *PostAuthRecoverAccessInternalServerError) GetPayload() *models.AuthErrorResponse {
	return o.Payload
}

func (o *PostAuthRecoverAccessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
