// Code generated by go-swagger; DO NOT EDIT.

package dto

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoPostResponse dto post response
//
// swagger:model dto.PostResponse
type DtoPostResponse struct {

	// content
	Content string `json:"content,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// images
	Images []string `json:"images"`

	// org
	Org *DtoPostResponseOrg `json:"org,omitempty"`
}

// Validate validates this dto post response
func (m *DtoPostResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrg(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoPostResponse) validateOrg(formats strfmt.Registry) error {
	if swag.IsZero(m.Org) { // not required
		return nil
	}

	if m.Org != nil {
		if err := m.Org.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("org")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("org")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this dto post response based on the context it is used
func (m *DtoPostResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrg(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoPostResponse) contextValidateOrg(ctx context.Context, formats strfmt.Registry) error {

	if m.Org != nil {

		if swag.IsZero(m.Org) { // not required
			return nil
		}

		if err := m.Org.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("org")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("org")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DtoPostResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoPostResponse) UnmarshalBinary(b []byte) error {
	var res DtoPostResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DtoPostResponseOrg dto post response org
//
// swagger:model DtoPostResponseOrg
type DtoPostResponseOrg struct {

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// profile type
	ProfileType string `json:"profileType,omitempty"`
}

// Validate validates this dto post response org
func (m *DtoPostResponseOrg) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto post response org based on context it is used
func (m *DtoPostResponseOrg) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoPostResponseOrg) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoPostResponseOrg) UnmarshalBinary(b []byte) error {
	var res DtoPostResponseOrg
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
