// Code generated by go-swagger; DO NOT EDIT.

package dto

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlerBusinessVenueResponse handler business venue response
//
// swagger:model handler_business.venueResponse
type HandlerBusinessVenueResponse struct {

	// avatar
	// Example: https://cdn.example.com/avatar.png
	Avatar string `json:"avatar,omitempty"`

	// banner
	// Example: https://cdn.example.com/banner.png
	Banner string `json:"banner,omitempty"`

	// description
	// Example: A cozy place in the city center.
	Description string `json:"description,omitempty"`

	// id
	// Example: 3
	ID int64 `json:"id,omitempty"`

	// name
	// Example: ShareBite Downtown
	Name string `json:"name,omitempty"`
}

// Validate validates this handler business venue response
func (m *HandlerBusinessVenueResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handler business venue response based on context it is used
func (m *HandlerBusinessVenueResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlerBusinessVenueResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlerBusinessVenueResponse) UnmarshalBinary(b []byte) error {
	var res HandlerBusinessVenueResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
