// Code generated by go-swagger; DO NOT EDIT.

package dto

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalBusinessHandlerBusinessErrorResponse internal business handler business error response
//
// swagger:model internal_business_handler_business.errorResponse
type InternalBusinessHandlerBusinessErrorResponse struct {

	// error
	// Example: not found
	Error string `json:"error,omitempty"`
}

// Validate validates this internal business handler business error response
func (m *InternalBusinessHandlerBusinessErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal business handler business error response based on context it is used
func (m *InternalBusinessHandlerBusinessErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessErrorResponse) UnmarshalBinary(b []byte) error {
	var res InternalBusinessHandlerBusinessErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
