// Code generated by go-swagger; DO NOT EDIT.

package dto

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalBusinessHandlerBusinessListItem internal business handler business list item
//
// swagger:model internal_business_handler_business.listItem
type InternalBusinessHandlerBusinessListItem struct {

	// avatar
	// Example: https://cdn.example.com/avatar.png
	Avatar string `json:"avatar,omitempty"`

	// description
	// Example: A cozy place in the city center.
	Description string `json:"description,omitempty"`

	// id
	// Example: 42
	ID int64 `json:"id,omitempty"`

	// latitude
	// Example: 50.4501
	Latitude float64 `json:"latitude,omitempty"`

	// longitude
	// Example: 30.5234
	Longitude float64 `json:"longitude,omitempty"`

	// name
	// Example: ShareBite Downtown
	Name string `json:"name,omitempty"`
}

// Validate validates this internal business handler business list item
func (m *InternalBusinessHandlerBusinessListItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal business handler business list item based on context it is used
func (m *InternalBusinessHandlerBusinessListItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessListItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessListItem) UnmarshalBinary(b []byte) error {
	var res InternalBusinessHandlerBusinessListItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
