// Code generated by go-swagger; DO NOT EDIT.

package dto

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InternalBusinessHandlerBusinessGetVenuesByIDsRequest internal business handler business get venues by IDs request
//
// swagger:model internal_business_handler_business.getVenuesByIDsRequest
type InternalBusinessHandlerBusinessGetVenuesByIDsRequest struct {

	// ids
	// Example: [3]
	// Required: true
	// Min Items: 1
	Ids []int64 `json:"ids"`
}

// Validate validates this internal business handler business get venues by IDs request
func (m *InternalBusinessHandlerBusinessGetVenuesByIDsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalBusinessHandlerBusinessGetVenuesByIDsRequest) validateIds(formats strfmt.Registry) error {

	if err := validate.Required("ids", "body", m.Ids); err != nil {
		return err
	}

	iIdsSize := int64(len(m.Ids))

	if err := validate.MinItems("ids", "body", iIdsSize, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this internal business handler business get venues by IDs request based on context it is used
func (m *InternalBusinessHandlerBusinessGetVenuesByIDsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessGetVenuesByIDsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessGetVenuesByIDsRequest) UnmarshalBinary(b []byte) error {
	var res InternalBusinessHandlerBusinessGetVenuesByIDsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
