// Code generated by go-swagger; DO NOT EDIT.

package dto

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InternalBusinessHandlerBusinessGetResponse internal business handler business get response
//
// swagger:model internal_business_handler_business.getResponse
type InternalBusinessHandlerBusinessGetResponse struct {

	// avatar
	// Example: https://cdn.example.com/avatar.png
	Avatar string `json:"avatar,omitempty"`

	// banner
	// Example: https://cdn.example.com/banner.png
	Banner string `json:"banner,omitempty"`

	// brand
	Brand *InternalBusinessHandlerBusinessBrandResponse `json:"brand,omitempty"`

	// description
	// Example: A cozy place in the city center.
	Description string `json:"description,omitempty"`

	// id
	// Example: 42
	ID int64 `json:"id,omitempty"`

	// latitude
	// Example: 50.4501
	Latitude float64 `json:"latitude,omitempty"`

	// longitude
	// Example: 30.5234
	Longitude float64 `json:"longitude,omitempty"`

	// name
	// Example: ShareBite Downtown
	Name string `json:"name,omitempty"`
}

// Validate validates this internal business handler business get response
func (m *InternalBusinessHandlerBusinessGetResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBrand(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalBusinessHandlerBusinessGetResponse) validateBrand(formats strfmt.Registry) error {
	if swag.IsZero(m.Brand) { // not required
		return nil
	}

	if m.Brand != nil {
		if err := m.Brand.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("brand")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("brand")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this internal business handler business get response based on the context it is used
func (m *InternalBusinessHandlerBusinessGetResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBrand(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalBusinessHandlerBusinessGetResponse) contextValidateBrand(ctx context.Context, formats strfmt.Registry) error {

	if m.Brand != nil {

		if swag.IsZero(m.Brand) { // not required
			return nil
		}

		if err := m.Brand.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("brand")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("brand")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessGetResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalBusinessHandlerBusinessGetResponse) UnmarshalBinary(b []byte) error {
	var res InternalBusinessHandlerBusinessGetResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
