FROM golang:1.25.1-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
RUN go build -o guest cmd/guest-api/main.go

FROM ubuntu:22.04
WORKDIR /app

COPY --from=builder /app/guest .

EXPOSE 3800

CMD ["./guest"]
