FROM golang:1.25.1-alpine3.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=false
ENV GOOSE=linux
RUN go build -o business cmd/business-api/main.go

FROM alpine:3.22
WORKDIR /app

COPY --from=builder /app/business .

EXPOSE 3900

CMD ["./business"]
