FROM golang:1.25.1-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
RUN go build -o admin-auth cmd/admin-auth-api/main.go

FROM ubuntu:22.04
WORKDIR /app

COPY --from=builder /app/admin-auth .

EXPOSE 3850

CMD ["./admin-auth"]
