nameOverride: ""
alertmanager:
  enabled: false
grafana:
  enabled: true
  fullnameOverride: "grafana"
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
prometheusOperator:
  fullnameOverride: "prometheus-operator"
  enabled: true
kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
kubelet:
  serviceMonitor:
    enabled: true
    interval: "15s"
prometheus:
  fullnameOverride: "prometheus"
  serviceAccount:
    create: true
    name: "prometheus-k8s"
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    retention: 10d
prometheus-node-exporter:
  fullnameOverride: "node-exporter"
  prometheus:
    monitor:
      enabled: true
      interval: "15s"
