// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBusinessOrgUnitsIDParams creates a new GetBusinessOrgUnitsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBusinessOrgUnitsIDParams() *GetBusinessOrgUnitsIDParams {
	return &GetBusinessOrgUnitsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBusinessOrgUnitsIDParamsWithTimeout creates a new GetBusinessOrgUnitsIDParams object
// with the ability to set a timeout on a request.
func NewGetBusinessOrgUnitsIDParamsWithTimeout(timeout time.Duration) *GetBusinessOrgUnitsIDParams {
	return &GetBusinessOrgUnitsIDParams{
		timeout: timeout,
	}
}

// NewGetBusinessOrgUnitsIDParamsWithContext creates a new GetBusinessOrgUnitsIDParams object
// with the ability to set a context for a request.
func NewGetBusinessOrgUnitsIDParamsWithContext(ctx context.Context) *GetBusinessOrgUnitsIDParams {
	return &GetBusinessOrgUnitsIDParams{
		Context: ctx,
	}
}

// NewGetBusinessOrgUnitsIDParamsWithHTTPClient creates a new GetBusinessOrgUnitsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBusinessOrgUnitsIDParamsWithHTTPClient(client *http.Client) *GetBusinessOrgUnitsIDParams {
	return &GetBusinessOrgUnitsIDParams{
		HTTPClient: client,
	}
}

/*
GetBusinessOrgUnitsIDParams contains all the parameters to send to the API endpoint

	for the get business org units ID operation.

	Typically these are written to a http.Request.
*/
type GetBusinessOrgUnitsIDParams struct {

	/* ID.

	   Location ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get business org units ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessOrgUnitsIDParams) WithDefaults() *GetBusinessOrgUnitsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get business org units ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessOrgUnitsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) WithTimeout(timeout time.Duration) *GetBusinessOrgUnitsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) WithContext(ctx context.Context) *GetBusinessOrgUnitsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) WithHTTPClient(client *http.Client) *GetBusinessOrgUnitsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) WithID(id int64) *GetBusinessOrgUnitsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get business org units ID params
func (o *GetBusinessOrgUnitsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBusinessOrgUnitsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
