// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// GetBusinessOrgUnitsIDReader is a Reader for the GetBusinessOrgUnitsID structure.
type GetBusinessOrgUnitsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBusinessOrgUnitsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetBusinessOrgUnitsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBusinessOrgUnitsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBusinessOrgUnitsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBusinessOrgUnitsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /business/org-units/{id}] GetBusinessOrgUnitsID", response, response.Code())
	}
}

// NewGetBusinessOrgUnitsIDOK creates a GetBusinessOrgUnitsIDOK with default headers values
func NewGetBusinessOrgUnitsIDOK() *GetBusinessOrgUnitsIDOK {
	return &GetBusinessOrgUnitsIDOK{}
}

/*
GetBusinessOrgUnitsIDOK describes a response with status code 200, with default header values.

OK
*/
type GetBusinessOrgUnitsIDOK struct {
	Payload *dto.HandlerBusinessGetResponse
}

// IsSuccess returns true when this get business org units Id o k response has a 2xx status code
func (o *GetBusinessOrgUnitsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get business org units Id o k response has a 3xx status code
func (o *GetBusinessOrgUnitsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business org units Id o k response has a 4xx status code
func (o *GetBusinessOrgUnitsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business org units Id o k response has a 5xx status code
func (o *GetBusinessOrgUnitsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get business org units Id o k response a status code equal to that given
func (o *GetBusinessOrgUnitsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get business org units Id o k response
func (o *GetBusinessOrgUnitsIDOK) Code() int {
	return 200
}

func (o *GetBusinessOrgUnitsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdOK %s", 200, payload)
}

func (o *GetBusinessOrgUnitsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdOK %s", 200, payload)
}

func (o *GetBusinessOrgUnitsIDOK) GetPayload() *dto.HandlerBusinessGetResponse {
	return o.Payload
}

func (o *GetBusinessOrgUnitsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessOrgUnitsIDBadRequest creates a GetBusinessOrgUnitsIDBadRequest with default headers values
func NewGetBusinessOrgUnitsIDBadRequest() *GetBusinessOrgUnitsIDBadRequest {
	return &GetBusinessOrgUnitsIDBadRequest{}
}

/*
GetBusinessOrgUnitsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetBusinessOrgUnitsIDBadRequest struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business org units Id bad request response has a 2xx status code
func (o *GetBusinessOrgUnitsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business org units Id bad request response has a 3xx status code
func (o *GetBusinessOrgUnitsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business org units Id bad request response has a 4xx status code
func (o *GetBusinessOrgUnitsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get business org units Id bad request response has a 5xx status code
func (o *GetBusinessOrgUnitsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get business org units Id bad request response a status code equal to that given
func (o *GetBusinessOrgUnitsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get business org units Id bad request response
func (o *GetBusinessOrgUnitsIDBadRequest) Code() int {
	return 400
}

func (o *GetBusinessOrgUnitsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdBadRequest %s", 400, payload)
}

func (o *GetBusinessOrgUnitsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdBadRequest %s", 400, payload)
}

func (o *GetBusinessOrgUnitsIDBadRequest) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessOrgUnitsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessOrgUnitsIDNotFound creates a GetBusinessOrgUnitsIDNotFound with default headers values
func NewGetBusinessOrgUnitsIDNotFound() *GetBusinessOrgUnitsIDNotFound {
	return &GetBusinessOrgUnitsIDNotFound{}
}

/*
GetBusinessOrgUnitsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetBusinessOrgUnitsIDNotFound struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business org units Id not found response has a 2xx status code
func (o *GetBusinessOrgUnitsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business org units Id not found response has a 3xx status code
func (o *GetBusinessOrgUnitsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business org units Id not found response has a 4xx status code
func (o *GetBusinessOrgUnitsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get business org units Id not found response has a 5xx status code
func (o *GetBusinessOrgUnitsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get business org units Id not found response a status code equal to that given
func (o *GetBusinessOrgUnitsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get business org units Id not found response
func (o *GetBusinessOrgUnitsIDNotFound) Code() int {
	return 404
}

func (o *GetBusinessOrgUnitsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdNotFound %s", 404, payload)
}

func (o *GetBusinessOrgUnitsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdNotFound %s", 404, payload)
}

func (o *GetBusinessOrgUnitsIDNotFound) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessOrgUnitsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessOrgUnitsIDInternalServerError creates a GetBusinessOrgUnitsIDInternalServerError with default headers values
func NewGetBusinessOrgUnitsIDInternalServerError() *GetBusinessOrgUnitsIDInternalServerError {
	return &GetBusinessOrgUnitsIDInternalServerError{}
}

/*
GetBusinessOrgUnitsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetBusinessOrgUnitsIDInternalServerError struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business org units Id internal server error response has a 2xx status code
func (o *GetBusinessOrgUnitsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business org units Id internal server error response has a 3xx status code
func (o *GetBusinessOrgUnitsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business org units Id internal server error response has a 4xx status code
func (o *GetBusinessOrgUnitsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business org units Id internal server error response has a 5xx status code
func (o *GetBusinessOrgUnitsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get business org units Id internal server error response a status code equal to that given
func (o *GetBusinessOrgUnitsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get business org units Id internal server error response
func (o *GetBusinessOrgUnitsIDInternalServerError) Code() int {
	return 500
}

func (o *GetBusinessOrgUnitsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdInternalServerError %s", 500, payload)
}

func (o *GetBusinessOrgUnitsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}][%d] getBusinessOrgUnitsIdInternalServerError %s", 500, payload)
}

func (o *GetBusinessOrgUnitsIDInternalServerError) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessOrgUnitsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
