// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// GetBusinessIDLocationsReader is a Reader for the GetBusinessIDLocations structure.
type GetBusinessIDLocationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBusinessIDLocationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetBusinessIDLocationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBusinessIDLocationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBusinessIDLocationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /business/{id}/locations] GetBusinessIDLocations", response, response.Code())
	}
}

// NewGetBusinessIDLocationsOK creates a GetBusinessIDLocationsOK with default headers values
func NewGetBusinessIDLocationsOK() *GetBusinessIDLocationsOK {
	return &GetBusinessIDLocationsOK{}
}

/*
GetBusinessIDLocationsOK describes a response with status code 200, with default header values.

OK
*/
type GetBusinessIDLocationsOK struct {
	Payload *dto.InternalBusinessHandlerBusinessListResponse
}

// IsSuccess returns true when this get business Id locations o k response has a 2xx status code
func (o *GetBusinessIDLocationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get business Id locations o k response has a 3xx status code
func (o *GetBusinessIDLocationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business Id locations o k response has a 4xx status code
func (o *GetBusinessIDLocationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business Id locations o k response has a 5xx status code
func (o *GetBusinessIDLocationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get business Id locations o k response a status code equal to that given
func (o *GetBusinessIDLocationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get business Id locations o k response
func (o *GetBusinessIDLocationsOK) Code() int {
	return 200
}

func (o *GetBusinessIDLocationsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}/locations][%d] getBusinessIdLocationsOK %s", 200, payload)
}

func (o *GetBusinessIDLocationsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}/locations][%d] getBusinessIdLocationsOK %s", 200, payload)
}

func (o *GetBusinessIDLocationsOK) GetPayload() *dto.InternalBusinessHandlerBusinessListResponse {
	return o.Payload
}

func (o *GetBusinessIDLocationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessIDLocationsBadRequest creates a GetBusinessIDLocationsBadRequest with default headers values
func NewGetBusinessIDLocationsBadRequest() *GetBusinessIDLocationsBadRequest {
	return &GetBusinessIDLocationsBadRequest{}
}

/*
GetBusinessIDLocationsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetBusinessIDLocationsBadRequest struct {
	Payload *dto.InternalBusinessHandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business Id locations bad request response has a 2xx status code
func (o *GetBusinessIDLocationsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business Id locations bad request response has a 3xx status code
func (o *GetBusinessIDLocationsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business Id locations bad request response has a 4xx status code
func (o *GetBusinessIDLocationsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get business Id locations bad request response has a 5xx status code
func (o *GetBusinessIDLocationsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get business Id locations bad request response a status code equal to that given
func (o *GetBusinessIDLocationsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get business Id locations bad request response
func (o *GetBusinessIDLocationsBadRequest) Code() int {
	return 400
}

func (o *GetBusinessIDLocationsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}/locations][%d] getBusinessIdLocationsBadRequest %s", 400, payload)
}

func (o *GetBusinessIDLocationsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}/locations][%d] getBusinessIdLocationsBadRequest %s", 400, payload)
}

func (o *GetBusinessIDLocationsBadRequest) GetPayload() *dto.InternalBusinessHandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessIDLocationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessIDLocationsInternalServerError creates a GetBusinessIDLocationsInternalServerError with default headers values
func NewGetBusinessIDLocationsInternalServerError() *GetBusinessIDLocationsInternalServerError {
	return &GetBusinessIDLocationsInternalServerError{}
}

/*
GetBusinessIDLocationsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetBusinessIDLocationsInternalServerError struct {
	Payload *dto.InternalBusinessHandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business Id locations internal server error response has a 2xx status code
func (o *GetBusinessIDLocationsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business Id locations internal server error response has a 3xx status code
func (o *GetBusinessIDLocationsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business Id locations internal server error response has a 4xx status code
func (o *GetBusinessIDLocationsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business Id locations internal server error response has a 5xx status code
func (o *GetBusinessIDLocationsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get business Id locations internal server error response a status code equal to that given
func (o *GetBusinessIDLocationsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get business Id locations internal server error response
func (o *GetBusinessIDLocationsInternalServerError) Code() int {
	return 500
}

func (o *GetBusinessIDLocationsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}/locations][%d] getBusinessIdLocationsInternalServerError %s", 500, payload)
}

func (o *GetBusinessIDLocationsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}/locations][%d] getBusinessIdLocationsInternalServerError %s", 500, payload)
}

func (o *GetBusinessIDLocationsInternalServerError) GetPayload() *dto.InternalBusinessHandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessIDLocationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
