// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBusinessIDParams creates a new GetBusinessIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBusinessIDParams() *GetBusinessIDParams {
	return &GetBusinessIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBusinessIDParamsWithTimeout creates a new GetBusinessIDParams object
// with the ability to set a timeout on a request.
func NewGetBusinessIDParamsWithTimeout(timeout time.Duration) *GetBusinessIDParams {
	return &GetBusinessIDParams{
		timeout: timeout,
	}
}

// NewGetBusinessIDParamsWithContext creates a new GetBusinessIDParams object
// with the ability to set a context for a request.
func NewGetBusinessIDParamsWithContext(ctx context.Context) *GetBusinessIDParams {
	return &GetBusinessIDParams{
		Context: ctx,
	}
}

// NewGetBusinessIDParamsWithHTTPClient creates a new GetBusinessIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBusinessIDParamsWithHTTPClient(client *http.Client) *GetBusinessIDParams {
	return &GetBusinessIDParams{
		HTTPClient: client,
	}
}

/*
GetBusinessIDParams contains all the parameters to send to the API endpoint

	for the get business ID operation.

	Typically these are written to a http.Request.
*/
type GetBusinessIDParams struct {

	/* ID.

	   Location ID
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get business ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessIDParams) WithDefaults() *GetBusinessIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get business ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get business ID params
func (o *GetBusinessIDParams) WithTimeout(timeout time.Duration) *GetBusinessIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get business ID params
func (o *GetBusinessIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get business ID params
func (o *GetBusinessIDParams) WithContext(ctx context.Context) *GetBusinessIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get business ID params
func (o *GetBusinessIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get business ID params
func (o *GetBusinessIDParams) WithHTTPClient(client *http.Client) *GetBusinessIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get business ID params
func (o *GetBusinessIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get business ID params
func (o *GetBusinessIDParams) WithID(id int64) *GetBusinessIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get business ID params
func (o *GetBusinessIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBusinessIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
