// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// GetBusinessOrgUnitsIDLocationsReader is a Reader for the GetBusinessOrgUnitsIDLocations structure.
type GetBusinessOrgUnitsIDLocationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBusinessOrgUnitsIDLocationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetBusinessOrgUnitsIDLocationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBusinessOrgUnitsIDLocationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBusinessOrgUnitsIDLocationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /business/org-units/{id}/locations] GetBusinessOrgUnitsIDLocations", response, response.Code())
	}
}

// NewGetBusinessOrgUnitsIDLocationsOK creates a GetBusinessOrgUnitsIDLocationsOK with default headers values
func NewGetBusinessOrgUnitsIDLocationsOK() *GetBusinessOrgUnitsIDLocationsOK {
	return &GetBusinessOrgUnitsIDLocationsOK{}
}

/*
GetBusinessOrgUnitsIDLocationsOK describes a response with status code 200, with default header values.

OK
*/
type GetBusinessOrgUnitsIDLocationsOK struct {
	Payload *dto.HandlerBusinessListResponse
}

// IsSuccess returns true when this get business org units Id locations o k response has a 2xx status code
func (o *GetBusinessOrgUnitsIDLocationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get business org units Id locations o k response has a 3xx status code
func (o *GetBusinessOrgUnitsIDLocationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business org units Id locations o k response has a 4xx status code
func (o *GetBusinessOrgUnitsIDLocationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business org units Id locations o k response has a 5xx status code
func (o *GetBusinessOrgUnitsIDLocationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get business org units Id locations o k response a status code equal to that given
func (o *GetBusinessOrgUnitsIDLocationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get business org units Id locations o k response
func (o *GetBusinessOrgUnitsIDLocationsOK) Code() int {
	return 200
}

func (o *GetBusinessOrgUnitsIDLocationsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}/locations][%d] getBusinessOrgUnitsIdLocationsOK %s", 200, payload)
}

func (o *GetBusinessOrgUnitsIDLocationsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}/locations][%d] getBusinessOrgUnitsIdLocationsOK %s", 200, payload)
}

func (o *GetBusinessOrgUnitsIDLocationsOK) GetPayload() *dto.HandlerBusinessListResponse {
	return o.Payload
}

func (o *GetBusinessOrgUnitsIDLocationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessOrgUnitsIDLocationsBadRequest creates a GetBusinessOrgUnitsIDLocationsBadRequest with default headers values
func NewGetBusinessOrgUnitsIDLocationsBadRequest() *GetBusinessOrgUnitsIDLocationsBadRequest {
	return &GetBusinessOrgUnitsIDLocationsBadRequest{}
}

/*
GetBusinessOrgUnitsIDLocationsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetBusinessOrgUnitsIDLocationsBadRequest struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business org units Id locations bad request response has a 2xx status code
func (o *GetBusinessOrgUnitsIDLocationsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business org units Id locations bad request response has a 3xx status code
func (o *GetBusinessOrgUnitsIDLocationsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business org units Id locations bad request response has a 4xx status code
func (o *GetBusinessOrgUnitsIDLocationsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get business org units Id locations bad request response has a 5xx status code
func (o *GetBusinessOrgUnitsIDLocationsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get business org units Id locations bad request response a status code equal to that given
func (o *GetBusinessOrgUnitsIDLocationsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get business org units Id locations bad request response
func (o *GetBusinessOrgUnitsIDLocationsBadRequest) Code() int {
	return 400
}

func (o *GetBusinessOrgUnitsIDLocationsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}/locations][%d] getBusinessOrgUnitsIdLocationsBadRequest %s", 400, payload)
}

func (o *GetBusinessOrgUnitsIDLocationsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}/locations][%d] getBusinessOrgUnitsIdLocationsBadRequest %s", 400, payload)
}

func (o *GetBusinessOrgUnitsIDLocationsBadRequest) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessOrgUnitsIDLocationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessOrgUnitsIDLocationsInternalServerError creates a GetBusinessOrgUnitsIDLocationsInternalServerError with default headers values
func NewGetBusinessOrgUnitsIDLocationsInternalServerError() *GetBusinessOrgUnitsIDLocationsInternalServerError {
	return &GetBusinessOrgUnitsIDLocationsInternalServerError{}
}

/*
GetBusinessOrgUnitsIDLocationsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetBusinessOrgUnitsIDLocationsInternalServerError struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business org units Id locations internal server error response has a 2xx status code
func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business org units Id locations internal server error response has a 3xx status code
func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business org units Id locations internal server error response has a 4xx status code
func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business org units Id locations internal server error response has a 5xx status code
func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get business org units Id locations internal server error response a status code equal to that given
func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get business org units Id locations internal server error response
func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) Code() int {
	return 500
}

func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}/locations][%d] getBusinessOrgUnitsIdLocationsInternalServerError %s", 500, payload)
}

func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/org-units/{id}/locations][%d] getBusinessOrgUnitsIdLocationsInternalServerError %s", 500, payload)
}

func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessOrgUnitsIDLocationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
