// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// GetBusinessIDReader is a Reader for the GetBusinessID structure.
type GetBusinessIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBusinessIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetBusinessIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBusinessIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBusinessIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBusinessIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /business/{id}] GetBusinessID", response, response.Code())
	}
}

// NewGetBusinessIDOK creates a GetBusinessIDOK with default headers values
func NewGetBusinessIDOK() *GetBusinessIDOK {
	return &GetBusinessIDOK{}
}

/*
GetBusinessIDOK describes a response with status code 200, with default header values.

OK
*/
type GetBusinessIDOK struct {
	Payload *dto.InternalBusinessHandlerBusinessGetResponse
}

// IsSuccess returns true when this get business Id o k response has a 2xx status code
func (o *GetBusinessIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get business Id o k response has a 3xx status code
func (o *GetBusinessIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business Id o k response has a 4xx status code
func (o *GetBusinessIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business Id o k response has a 5xx status code
func (o *GetBusinessIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get business Id o k response a status code equal to that given
func (o *GetBusinessIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get business Id o k response
func (o *GetBusinessIDOK) Code() int {
	return 200
}

func (o *GetBusinessIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdOK %s", 200, payload)
}

func (o *GetBusinessIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdOK %s", 200, payload)
}

func (o *GetBusinessIDOK) GetPayload() *dto.InternalBusinessHandlerBusinessGetResponse {
	return o.Payload
}

func (o *GetBusinessIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessIDBadRequest creates a GetBusinessIDBadRequest with default headers values
func NewGetBusinessIDBadRequest() *GetBusinessIDBadRequest {
	return &GetBusinessIDBadRequest{}
}

/*
GetBusinessIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetBusinessIDBadRequest struct {
	Payload *dto.InternalBusinessHandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business Id bad request response has a 2xx status code
func (o *GetBusinessIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business Id bad request response has a 3xx status code
func (o *GetBusinessIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business Id bad request response has a 4xx status code
func (o *GetBusinessIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get business Id bad request response has a 5xx status code
func (o *GetBusinessIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get business Id bad request response a status code equal to that given
func (o *GetBusinessIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get business Id bad request response
func (o *GetBusinessIDBadRequest) Code() int {
	return 400
}

func (o *GetBusinessIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdBadRequest %s", 400, payload)
}

func (o *GetBusinessIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdBadRequest %s", 400, payload)
}

func (o *GetBusinessIDBadRequest) GetPayload() *dto.InternalBusinessHandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessIDNotFound creates a GetBusinessIDNotFound with default headers values
func NewGetBusinessIDNotFound() *GetBusinessIDNotFound {
	return &GetBusinessIDNotFound{}
}

/*
GetBusinessIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetBusinessIDNotFound struct {
	Payload *dto.InternalBusinessHandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business Id not found response has a 2xx status code
func (o *GetBusinessIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business Id not found response has a 3xx status code
func (o *GetBusinessIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business Id not found response has a 4xx status code
func (o *GetBusinessIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get business Id not found response has a 5xx status code
func (o *GetBusinessIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get business Id not found response a status code equal to that given
func (o *GetBusinessIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get business Id not found response
func (o *GetBusinessIDNotFound) Code() int {
	return 404
}

func (o *GetBusinessIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdNotFound %s", 404, payload)
}

func (o *GetBusinessIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdNotFound %s", 404, payload)
}

func (o *GetBusinessIDNotFound) GetPayload() *dto.InternalBusinessHandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetBusinessIDInternalServerError creates a GetBusinessIDInternalServerError with default headers values
func NewGetBusinessIDInternalServerError() *GetBusinessIDInternalServerError {
	return &GetBusinessIDInternalServerError{}
}

/*
GetBusinessIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetBusinessIDInternalServerError struct {
	Payload *dto.InternalBusinessHandlerBusinessErrorResponse
}

// IsSuccess returns true when this get business Id internal server error response has a 2xx status code
func (o *GetBusinessIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get business Id internal server error response has a 3xx status code
func (o *GetBusinessIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get business Id internal server error response has a 4xx status code
func (o *GetBusinessIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get business Id internal server error response has a 5xx status code
func (o *GetBusinessIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get business Id internal server error response a status code equal to that given
func (o *GetBusinessIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get business Id internal server error response
func (o *GetBusinessIDInternalServerError) Code() int {
	return 500
}

func (o *GetBusinessIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdInternalServerError %s", 500, payload)
}

func (o *GetBusinessIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /business/{id}][%d] getBusinessIdInternalServerError %s", 500, payload)
}

func (o *GetBusinessIDInternalServerError) GetPayload() *dto.InternalBusinessHandlerBusinessErrorResponse {
	return o.Payload
}

func (o *GetBusinessIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
