// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBusinessOrgUnitsIDLocationsParams creates a new GetBusinessOrgUnitsIDLocationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBusinessOrgUnitsIDLocationsParams() *GetBusinessOrgUnitsIDLocationsParams {
	return &GetBusinessOrgUnitsIDLocationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBusinessOrgUnitsIDLocationsParamsWithTimeout creates a new GetBusinessOrgUnitsIDLocationsParams object
// with the ability to set a timeout on a request.
func NewGetBusinessOrgUnitsIDLocationsParamsWithTimeout(timeout time.Duration) *GetBusinessOrgUnitsIDLocationsParams {
	return &GetBusinessOrgUnitsIDLocationsParams{
		timeout: timeout,
	}
}

// NewGetBusinessOrgUnitsIDLocationsParamsWithContext creates a new GetBusinessOrgUnitsIDLocationsParams object
// with the ability to set a context for a request.
func NewGetBusinessOrgUnitsIDLocationsParamsWithContext(ctx context.Context) *GetBusinessOrgUnitsIDLocationsParams {
	return &GetBusinessOrgUnitsIDLocationsParams{
		Context: ctx,
	}
}

// NewGetBusinessOrgUnitsIDLocationsParamsWithHTTPClient creates a new GetBusinessOrgUnitsIDLocationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBusinessOrgUnitsIDLocationsParamsWithHTTPClient(client *http.Client) *GetBusinessOrgUnitsIDLocationsParams {
	return &GetBusinessOrgUnitsIDLocationsParams{
		HTTPClient: client,
	}
}

/*
GetBusinessOrgUnitsIDLocationsParams contains all the parameters to send to the API endpoint

	for the get business org units ID locations operation.

	Typically these are written to a http.Request.
*/
type GetBusinessOrgUnitsIDLocationsParams struct {

	/* ID.

	   Brand ID
	*/
	ID int64

	/* Limit.

	   Items per page (default: 10, max: 100)
	*/
	Limit *int64

	/* Skip.

	   Number of items to skip (default: 0)
	*/
	Skip *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get business org units ID locations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessOrgUnitsIDLocationsParams) WithDefaults() *GetBusinessOrgUnitsIDLocationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get business org units ID locations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBusinessOrgUnitsIDLocationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) WithTimeout(timeout time.Duration) *GetBusinessOrgUnitsIDLocationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) WithContext(ctx context.Context) *GetBusinessOrgUnitsIDLocationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) WithHTTPClient(client *http.Client) *GetBusinessOrgUnitsIDLocationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) WithID(id int64) *GetBusinessOrgUnitsIDLocationsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) SetID(id int64) {
	o.ID = id
}

// WithLimit adds the limit to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) WithLimit(limit *int64) *GetBusinessOrgUnitsIDLocationsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSkip adds the skip to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) WithSkip(skip *int64) *GetBusinessOrgUnitsIDLocationsParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the get business org units ID locations params
func (o *GetBusinessOrgUnitsIDLocationsParams) SetSkip(skip *int64) {
	o.Skip = skip
}

// WriteToRequest writes these params to a swagger request
func (o *GetBusinessOrgUnitsIDLocationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int64

		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt64(qrSkip)
		if qSkip != "" {

			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
