// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AuthResetPasswordRequest auth reset password request
//
// swagger:model auth.ResetPasswordRequest
type AuthResetPasswordRequest struct {

	// new password
	// Required: true
	// Max Length: 72
	// Min Length: 8
	NewPassword *string `json:"new_password"`

	// token
	// Required: true
	Token *string `json:"token"`
}

// Validate validates this auth reset password request
func (m *AuthResetPasswordRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthResetPasswordRequest) validateNewPassword(formats strfmt.Registry) error {

	if err := validate.Required("new_password", "body", m.NewPassword); err != nil {
		return err
	}

	if err := validate.MinLength("new_password", "body", *m.NewPassword, 8); err != nil {
		return err
	}

	if err := validate.MaxLength("new_password", "body", *m.NewPassword, 72); err != nil {
		return err
	}

	return nil
}

func (m *AuthResetPasswordRequest) validateToken(formats strfmt.Registry) error {

	if err := validate.Required("token", "body", m.Token); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this auth reset password request based on context it is used
func (m *AuthResetPasswordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthResetPasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthResetPasswordRequest) UnmarshalBinary(b []byte) error {
	var res AuthResetPasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
