// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthErrorResponse auth error response
//
// swagger:model auth.ErrorResponse
type AuthErrorResponse struct {

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this auth error response
func (m *AuthErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth error response based on context it is used
func (m *AuthErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthErrorResponse) UnmarshalBinary(b []byte) error {
	var res AuthErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
