// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AuthRecoverAccessRequest auth recover access request
//
// swagger:model auth.RecoverAccessRequest
type AuthRecoverAccessRequest struct {

	// email
	// Required: true
	// Max Length: 254
	Email *string `json:"email"`
}

// Validate validates this auth recover access request
func (m *AuthRecoverAccessRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthRecoverAccessRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.MaxLength("email", "body", *m.Email, 254); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this auth recover access request based on context it is used
func (m *AuthRecoverAccessRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthRecoverAccessRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthRecoverAccessRequest) UnmarshalBinary(b []byte) error {
	var res AuthRecoverAccessRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
