// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthMessageResponse auth message response
//
// swagger:model auth.MessageResponse
type AuthMessageResponse struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this auth message response
func (m *AuthMessageResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth message response based on context it is used
func (m *AuthMessageResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthMessageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthMessageResponse) UnmarshalBinary(b []byte) error {
	var res AuthMessageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
