// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BusinessBrandResponse business brand response
//
// swagger:model business.brandResponse
type BusinessBrandResponse struct {

	// avatar
	// Example: https://cdn.example.com/brand-avatar.png
	Avatar string `json:"avatar,omitempty"`

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// name
	// Example: ShareBite HQ
	Name string `json:"name,omitempty"`
}

// Validate validates this business brand response
func (m *BusinessBrandResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this business brand response based on context it is used
func (m *BusinessBrandResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BusinessBrandResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BusinessBrandResponse) UnmarshalBinary(b []byte) error {
	var res BusinessBrandResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
