// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BusinessVenueResponse business venue response
//
// swagger:model business.venueResponse
type BusinessVenueResponse struct {

	// avatar
	// Example: https://cdn.example.com/avatar.png
	Avatar string `json:"avatar,omitempty"`

	// banner
	// Example: https://cdn.example.com/banner.png
	Banner string `json:"banner,omitempty"`

	// description
	// Example: A cozy place in the city center.
	Description string `json:"description,omitempty"`

	// id
	// Example: 3
	ID int64 `json:"id,omitempty"`

	// name
	// Example: ShareBite Downtown
	Name string `json:"name,omitempty"`
}

// Validate validates this business venue response
func (m *BusinessVenueResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this business venue response based on context it is used
func (m *BusinessVenueResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BusinessVenueResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BusinessVenueResponse) UnmarshalBinary(b []byte) error {
	var res BusinessVenueResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
