// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BusinessErrorResponse business error response
//
// swagger:model business.errorResponse
type BusinessErrorResponse struct {

	// error
	// Example: not found
	Error string `json:"error,omitempty"`
}

// Validate validates this business error response
func (m *BusinessErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this business error response based on context it is used
func (m *BusinessErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BusinessErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BusinessErrorResponse) UnmarshalBinary(b []byte) error {
	var res BusinessErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
