// Code generated by go-swagger; DO NOT EDIT.

package locations

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new locations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new locations API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new locations API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for locations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetBusinessOrgUnitsID(params *GetBusinessOrgUnitsIDParams, opts ...ClientOption) (*GetBusinessOrgUnitsIDOK, error)

	GetBusinessOrgUnitsIDLocations(params *GetBusinessOrgUnitsIDLocationsParams, opts ...ClientOption) (*GetBusinessOrgUnitsIDLocationsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetBusinessOrgUnitsID gets location by ID

Returns a single venue/location that belongs to a brand, including the parent brand info.
*/
func (a *Client) GetBusinessOrgUnitsID(params *GetBusinessOrgUnitsIDParams, opts ...ClientOption) (*GetBusinessOrgUnitsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetBusinessOrgUnitsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetBusinessOrgUnitsID",
		Method:             "GET",
		PathPattern:        "/business/org-units/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBusinessOrgUnitsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetBusinessOrgUnitsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetBusinessOrgUnitsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetBusinessOrgUnitsIDLocations lists brand locations

Returns a paginated list of venues/locations that belong to the given brand.
*/
func (a *Client) GetBusinessOrgUnitsIDLocations(params *GetBusinessOrgUnitsIDLocationsParams, opts ...ClientOption) (*GetBusinessOrgUnitsIDLocationsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetBusinessOrgUnitsIDLocationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetBusinessOrgUnitsIDLocations",
		Method:             "GET",
		PathPattern:        "/business/org-units/{id}/locations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBusinessOrgUnitsIDLocationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetBusinessOrgUnitsIDLocationsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetBusinessOrgUnitsIDLocations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
