// Code generated by go-swagger; DO NOT EDIT.

package venues

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// NewPostBusinessOrgUnitsVenuesParams creates a new PostBusinessOrgUnitsVenuesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostBusinessOrgUnitsVenuesParams() *PostBusinessOrgUnitsVenuesParams {
	return &PostBusinessOrgUnitsVenuesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostBusinessOrgUnitsVenuesParamsWithTimeout creates a new PostBusinessOrgUnitsVenuesParams object
// with the ability to set a timeout on a request.
func NewPostBusinessOrgUnitsVenuesParamsWithTimeout(timeout time.Duration) *PostBusinessOrgUnitsVenuesParams {
	return &PostBusinessOrgUnitsVenuesParams{
		timeout: timeout,
	}
}

// NewPostBusinessOrgUnitsVenuesParamsWithContext creates a new PostBusinessOrgUnitsVenuesParams object
// with the ability to set a context for a request.
func NewPostBusinessOrgUnitsVenuesParamsWithContext(ctx context.Context) *PostBusinessOrgUnitsVenuesParams {
	return &PostBusinessOrgUnitsVenuesParams{
		Context: ctx,
	}
}

// NewPostBusinessOrgUnitsVenuesParamsWithHTTPClient creates a new PostBusinessOrgUnitsVenuesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostBusinessOrgUnitsVenuesParamsWithHTTPClient(client *http.Client) *PostBusinessOrgUnitsVenuesParams {
	return &PostBusinessOrgUnitsVenuesParams{
		HTTPClient: client,
	}
}

/*
PostBusinessOrgUnitsVenuesParams contains all the parameters to send to the API endpoint

	for the post business org units venues operation.

	Typically these are written to a http.Request.
*/
type PostBusinessOrgUnitsVenuesParams struct {

	/* Request.

	   Array of venue IDs
	*/
	Request *dto.HandlerBusinessGetVenuesByIDsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post business org units venues params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBusinessOrgUnitsVenuesParams) WithDefaults() *PostBusinessOrgUnitsVenuesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post business org units venues params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBusinessOrgUnitsVenuesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) WithTimeout(timeout time.Duration) *PostBusinessOrgUnitsVenuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) WithContext(ctx context.Context) *PostBusinessOrgUnitsVenuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) WithHTTPClient(client *http.Client) *PostBusinessOrgUnitsVenuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) WithRequest(request *dto.HandlerBusinessGetVenuesByIDsRequest) *PostBusinessOrgUnitsVenuesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post business org units venues params
func (o *PostBusinessOrgUnitsVenuesParams) SetRequest(request *dto.HandlerBusinessGetVenuesByIDsRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostBusinessOrgUnitsVenuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
