// Code generated by go-swagger; DO NOT EDIT.

package venues

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// PostBusinessOrgUnitsVenuesReader is a Reader for the PostBusinessOrgUnitsVenues structure.
type PostBusinessOrgUnitsVenuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBusinessOrgUnitsVenuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostBusinessOrgUnitsVenuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostBusinessOrgUnitsVenuesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostBusinessOrgUnitsVenuesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /business/org-units/venues] PostBusinessOrgUnitsVenues", response, response.Code())
	}
}

// NewPostBusinessOrgUnitsVenuesOK creates a PostBusinessOrgUnitsVenuesOK with default headers values
func NewPostBusinessOrgUnitsVenuesOK() *PostBusinessOrgUnitsVenuesOK {
	return &PostBusinessOrgUnitsVenuesOK{}
}

/*
PostBusinessOrgUnitsVenuesOK describes a response with status code 200, with default header values.

OK
*/
type PostBusinessOrgUnitsVenuesOK struct {
	Payload []*dto.HandlerBusinessVenueResponse
}

// IsSuccess returns true when this post business org units venues o k response has a 2xx status code
func (o *PostBusinessOrgUnitsVenuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post business org units venues o k response has a 3xx status code
func (o *PostBusinessOrgUnitsVenuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post business org units venues o k response has a 4xx status code
func (o *PostBusinessOrgUnitsVenuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post business org units venues o k response has a 5xx status code
func (o *PostBusinessOrgUnitsVenuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post business org units venues o k response a status code equal to that given
func (o *PostBusinessOrgUnitsVenuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post business org units venues o k response
func (o *PostBusinessOrgUnitsVenuesOK) Code() int {
	return 200
}

func (o *PostBusinessOrgUnitsVenuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/org-units/venues][%d] postBusinessOrgUnitsVenuesOK %s", 200, payload)
}

func (o *PostBusinessOrgUnitsVenuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/org-units/venues][%d] postBusinessOrgUnitsVenuesOK %s", 200, payload)
}

func (o *PostBusinessOrgUnitsVenuesOK) GetPayload() []*dto.HandlerBusinessVenueResponse {
	return o.Payload
}

func (o *PostBusinessOrgUnitsVenuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostBusinessOrgUnitsVenuesBadRequest creates a PostBusinessOrgUnitsVenuesBadRequest with default headers values
func NewPostBusinessOrgUnitsVenuesBadRequest() *PostBusinessOrgUnitsVenuesBadRequest {
	return &PostBusinessOrgUnitsVenuesBadRequest{}
}

/*
PostBusinessOrgUnitsVenuesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostBusinessOrgUnitsVenuesBadRequest struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this post business org units venues bad request response has a 2xx status code
func (o *PostBusinessOrgUnitsVenuesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post business org units venues bad request response has a 3xx status code
func (o *PostBusinessOrgUnitsVenuesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post business org units venues bad request response has a 4xx status code
func (o *PostBusinessOrgUnitsVenuesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post business org units venues bad request response has a 5xx status code
func (o *PostBusinessOrgUnitsVenuesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post business org units venues bad request response a status code equal to that given
func (o *PostBusinessOrgUnitsVenuesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post business org units venues bad request response
func (o *PostBusinessOrgUnitsVenuesBadRequest) Code() int {
	return 400
}

func (o *PostBusinessOrgUnitsVenuesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/org-units/venues][%d] postBusinessOrgUnitsVenuesBadRequest %s", 400, payload)
}

func (o *PostBusinessOrgUnitsVenuesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/org-units/venues][%d] postBusinessOrgUnitsVenuesBadRequest %s", 400, payload)
}

func (o *PostBusinessOrgUnitsVenuesBadRequest) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PostBusinessOrgUnitsVenuesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostBusinessOrgUnitsVenuesInternalServerError creates a PostBusinessOrgUnitsVenuesInternalServerError with default headers values
func NewPostBusinessOrgUnitsVenuesInternalServerError() *PostBusinessOrgUnitsVenuesInternalServerError {
	return &PostBusinessOrgUnitsVenuesInternalServerError{}
}

/*
PostBusinessOrgUnitsVenuesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostBusinessOrgUnitsVenuesInternalServerError struct {
	Payload *dto.HandlerBusinessErrorResponse
}

// IsSuccess returns true when this post business org units venues internal server error response has a 2xx status code
func (o *PostBusinessOrgUnitsVenuesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post business org units venues internal server error response has a 3xx status code
func (o *PostBusinessOrgUnitsVenuesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post business org units venues internal server error response has a 4xx status code
func (o *PostBusinessOrgUnitsVenuesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post business org units venues internal server error response has a 5xx status code
func (o *PostBusinessOrgUnitsVenuesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post business org units venues internal server error response a status code equal to that given
func (o *PostBusinessOrgUnitsVenuesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post business org units venues internal server error response
func (o *PostBusinessOrgUnitsVenuesInternalServerError) Code() int {
	return 500
}

func (o *PostBusinessOrgUnitsVenuesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/org-units/venues][%d] postBusinessOrgUnitsVenuesInternalServerError %s", 500, payload)
}

func (o *PostBusinessOrgUnitsVenuesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/org-units/venues][%d] postBusinessOrgUnitsVenuesInternalServerError %s", 500, payload)
}

func (o *PostBusinessOrgUnitsVenuesInternalServerError) GetPayload() *dto.HandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PostBusinessOrgUnitsVenuesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.HandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
