// Code generated by go-swagger; DO NOT EDIT.

package venues

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// PostBusinessVenuesReader is a Reader for the PostBusinessVenues structure.
type PostBusinessVenuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBusinessVenuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostBusinessVenuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostBusinessVenuesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostBusinessVenuesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /business/venues] PostBusinessVenues", response, response.Code())
	}
}

// NewPostBusinessVenuesOK creates a PostBusinessVenuesOK with default headers values
func NewPostBusinessVenuesOK() *PostBusinessVenuesOK {
	return &PostBusinessVenuesOK{}
}

/*
PostBusinessVenuesOK describes a response with status code 200, with default header values.

OK
*/
type PostBusinessVenuesOK struct {
	Payload []*dto.InternalBusinessHandlerBusinessVenueResponse
}

// IsSuccess returns true when this post business venues o k response has a 2xx status code
func (o *PostBusinessVenuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post business venues o k response has a 3xx status code
func (o *PostBusinessVenuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post business venues o k response has a 4xx status code
func (o *PostBusinessVenuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post business venues o k response has a 5xx status code
func (o *PostBusinessVenuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post business venues o k response a status code equal to that given
func (o *PostBusinessVenuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post business venues o k response
func (o *PostBusinessVenuesOK) Code() int {
	return 200
}

func (o *PostBusinessVenuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/venues][%d] postBusinessVenuesOK %s", 200, payload)
}

func (o *PostBusinessVenuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/venues][%d] postBusinessVenuesOK %s", 200, payload)
}

func (o *PostBusinessVenuesOK) GetPayload() []*dto.InternalBusinessHandlerBusinessVenueResponse {
	return o.Payload
}

func (o *PostBusinessVenuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostBusinessVenuesBadRequest creates a PostBusinessVenuesBadRequest with default headers values
func NewPostBusinessVenuesBadRequest() *PostBusinessVenuesBadRequest {
	return &PostBusinessVenuesBadRequest{}
}

/*
PostBusinessVenuesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostBusinessVenuesBadRequest struct {
	Payload *dto.InternalBusinessHandlerBusinessErrorResponse
}

// IsSuccess returns true when this post business venues bad request response has a 2xx status code
func (o *PostBusinessVenuesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post business venues bad request response has a 3xx status code
func (o *PostBusinessVenuesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post business venues bad request response has a 4xx status code
func (o *PostBusinessVenuesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post business venues bad request response has a 5xx status code
func (o *PostBusinessVenuesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post business venues bad request response a status code equal to that given
func (o *PostBusinessVenuesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post business venues bad request response
func (o *PostBusinessVenuesBadRequest) Code() int {
	return 400
}

func (o *PostBusinessVenuesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/venues][%d] postBusinessVenuesBadRequest %s", 400, payload)
}

func (o *PostBusinessVenuesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/venues][%d] postBusinessVenuesBadRequest %s", 400, payload)
}

func (o *PostBusinessVenuesBadRequest) GetPayload() *dto.InternalBusinessHandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PostBusinessVenuesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostBusinessVenuesInternalServerError creates a PostBusinessVenuesInternalServerError with default headers values
func NewPostBusinessVenuesInternalServerError() *PostBusinessVenuesInternalServerError {
	return &PostBusinessVenuesInternalServerError{}
}

/*
PostBusinessVenuesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostBusinessVenuesInternalServerError struct {
	Payload *dto.InternalBusinessHandlerBusinessErrorResponse
}

// IsSuccess returns true when this post business venues internal server error response has a 2xx status code
func (o *PostBusinessVenuesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post business venues internal server error response has a 3xx status code
func (o *PostBusinessVenuesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post business venues internal server error response has a 4xx status code
func (o *PostBusinessVenuesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post business venues internal server error response has a 5xx status code
func (o *PostBusinessVenuesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post business venues internal server error response a status code equal to that given
func (o *PostBusinessVenuesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post business venues internal server error response
func (o *PostBusinessVenuesInternalServerError) Code() int {
	return 500
}

func (o *PostBusinessVenuesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/venues][%d] postBusinessVenuesInternalServerError %s", 500, payload)
}

func (o *PostBusinessVenuesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /business/venues][%d] postBusinessVenuesInternalServerError %s", 500, payload)
}

func (o *PostBusinessVenuesInternalServerError) GetPayload() *dto.InternalBusinessHandlerBusinessErrorResponse {
	return o.Payload
}

func (o *PostBusinessVenuesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(dto.InternalBusinessHandlerBusinessErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
