// Code generated by go-swagger; DO NOT EDIT.

package venues

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ua-academy-projects/share-bite/internal/guest/gateway/business/client/dto"
)

// NewPostBusinessVenuesParams creates a new PostBusinessVenuesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostBusinessVenuesParams() *PostBusinessVenuesParams {
	return &PostBusinessVenuesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostBusinessVenuesParamsWithTimeout creates a new PostBusinessVenuesParams object
// with the ability to set a timeout on a request.
func NewPostBusinessVenuesParamsWithTimeout(timeout time.Duration) *PostBusinessVenuesParams {
	return &PostBusinessVenuesParams{
		timeout: timeout,
	}
}

// NewPostBusinessVenuesParamsWithContext creates a new PostBusinessVenuesParams object
// with the ability to set a context for a request.
func NewPostBusinessVenuesParamsWithContext(ctx context.Context) *PostBusinessVenuesParams {
	return &PostBusinessVenuesParams{
		Context: ctx,
	}
}

// NewPostBusinessVenuesParamsWithHTTPClient creates a new PostBusinessVenuesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostBusinessVenuesParamsWithHTTPClient(client *http.Client) *PostBusinessVenuesParams {
	return &PostBusinessVenuesParams{
		HTTPClient: client,
	}
}

/*
PostBusinessVenuesParams contains all the parameters to send to the API endpoint

	for the post business venues operation.

	Typically these are written to a http.Request.
*/
type PostBusinessVenuesParams struct {

	/* Request.

	   Array of venue IDs
	*/
	Request *dto.InternalBusinessHandlerBusinessGetVenuesByIDsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post business venues params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBusinessVenuesParams) WithDefaults() *PostBusinessVenuesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post business venues params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBusinessVenuesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post business venues params
func (o *PostBusinessVenuesParams) WithTimeout(timeout time.Duration) *PostBusinessVenuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post business venues params
func (o *PostBusinessVenuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post business venues params
func (o *PostBusinessVenuesParams) WithContext(ctx context.Context) *PostBusinessVenuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post business venues params
func (o *PostBusinessVenuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post business venues params
func (o *PostBusinessVenuesParams) WithHTTPClient(client *http.Client) *PostBusinessVenuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post business venues params
func (o *PostBusinessVenuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post business venues params
func (o *PostBusinessVenuesParams) WithRequest(request *dto.InternalBusinessHandlerBusinessGetVenuesByIDsRequest) *PostBusinessVenuesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post business venues params
func (o *PostBusinessVenuesParams) SetRequest(request *dto.InternalBusinessHandlerBusinessGetVenuesByIDsRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostBusinessVenuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
