apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: share-bite-local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-role
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: share-bite-local
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: share-bite-local
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: alloy
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: grafana/alloy:v1.1.0@sha256:d8a5568114fec8b3b3a726618d363d64bb661e7041a1a5b81a8c54c348f95c6f
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/var/lib/alloy
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: alloy-storage
              mountPath: /var/lib/alloy
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: alloy-storage
          emptyDir: {}