apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- cnpg.yaml 
# for StatefulSet - use postgres.yaml instead of cnpg.yaml
#- postgres.yaml
- redis.yaml
- secret.yaml
- migrator-job.yaml
