apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: share-bite-local
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: share-bite-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 10001
      containers:
        - name: loki
          image: grafana/loki:2.9.4@sha256:221d60ea262b92131972856db364ff0ffc3f910408ca42ce296df442fb0ce598
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 3100