apiVersion: v1
kind: Service
metadata:
  name: guest-api
  namespace: share-bite-local
spec:
  selector:
    app: guest-api
  ports:
    - name: http
      protocol: TCP
      port: 3800
      targetPort: 3800