apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guest-api-monitor
  namespace: share-bite-local
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - share-bite-local
  selector:
    matchLabels:
      app: guest-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
