// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/business/{id}": {
            "get": {
                "description": "Returns a single venue/location that belongs to a brand, including the parent brand info.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "locations"
                ],
                "summary": "Get location by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Location ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_business_handler_business.getResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_business_handler_business.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_business_handler_business.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_business_handler_business.errorResponse"
                        }
                    }
                }
            }
        },
        "/business/{id}/locations": {
            "get": {
                "description": "Returns a paginated list of venues/locations that belong to the given brand.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "locations"
                ],
                "summary": "List brand locations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Brand ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_business_handler_business.listResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_business_handler_business.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_business_handler_business.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_business_handler_business.brandResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://cdn.example.com/brand-avatar.png"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "ShareBite HQ"
                }
            }
        },
        "internal_business_handler_business.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "location with id 999 was not found"
                }
            }
        },
        "internal_business_handler_business.getResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://cdn.example.com/avatar.png"
                },
                "banner": {
                    "type": "string",
                    "example": "https://cdn.example.com/banner.png"
                },
                "brand": {
                    "$ref": "#/definitions/internal_business_handler_business.brandResponse"
                },
                "description": {
                    "type": "string",
                    "example": "A cozy place in the city center."
                },
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "latitude": {
                    "type": "number",
                    "example": 50.4501
                },
                "longitude": {
                    "type": "number",
                    "example": 30.5234
                },
                "name": {
                    "type": "string",
                    "example": "ShareBite Downtown"
                }
            }
        },
        "internal_business_handler_business.listItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://cdn.example.com/avatar.png"
                },
                "description": {
                    "type": "string",
                    "example": "A cozy place in the city center."
                },
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "latitude": {
                    "type": "number",
                    "example": 50.4501
                },
                "longitude": {
                    "type": "number",
                    "example": 30.5234
                },
                "name": {
                    "type": "string",
                    "example": "ShareBite Downtown"
                }
            }
        },
        "internal_business_handler_business.listResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_business_handler_business.listItem"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ShareBite Business API",
	Description:      "API for discovering brand locations (venues).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
